### PR TITLE
Update return type for get_native_mem() per SYCL 2020

### PR DESCRIPTION
**Pull request by againull**
Per "C.6. Interoperability with the OpenCL API" of the SYCL 2020
specification native type for sycl::buffer is std::vector<cl_mem>.

Update test accordingly.

Signed-off-by: Artur Gainullin <artur.gainullin@intel.com>

### CODE REVIEW

**Comment by againull** [comment]
Hi, could you please review this PR.

**Review by keryell — APPROVED** [review]
Thanks!

**Comment by againull** [comment]
Test fails because corresponding change in the dpcpp compiler was made in the commit 8b3c8c4 (Apr 22, 2022) while testing is performed with 977f22d compiler (Feb 26).

@bader @keryell Is there a way to update compiler in the testing? Or should I wait till the moment when it gets updated?

**Comment by bader** [comment]
@againull, here is an example how I updated DPC++ version last time - https://github.com/KhronosGroup/SYCL-CTS/pull/299. I hope process hasn't changed. @psalz, knows the process inside out.

**Comment by keryell** [comment]
Would it make sense to also test to the latest DPC++ to give a broader view, both for CTS and DPC++ developers?

**Comment by againull** [comment]
> Would it make sense to also test to the latest DPC++ to give a broader view, both for CTS and DPC++ developers?

Yes, I've created a PR to uplift the version to the latest nightly: https://github.com/KhronosGroup/SYCL-CTS/pull/340

**Comment by againull** [comment]
DPCPP version was uplifted, so this PR is ready to be merged now.

**Review by bader — APPROVED** [review]

**Pull request merged**
