### PR TITLE
Add -fpreview-breaking-changes flag to conformance mode for DPCPP

### PR DESCRIPTION
**Pull request by steffenlarsen**
The SYCL2020_CONFORMANT_APIS in DPCPP is being deprecated in favor of -fpreview-breaking-changes option. This patch adds this new option when conformant APIs are enabled for DPCPP while keeping the preprocessor macro for now.

### CODE REVIEW

**Comment by steffenlarsen** [comment]
This patch will need a DPC++ version bump.

**Comment by bader** [comment]
> This patch will need a DPC++ version bump.

@steffenlarsen, will you uplift the DPC++ version?

**Comment by bader** [comment]
> > This patch will need a DPC++ version bump.
> 
> @steffenlarsen, will you uplift the DPC++ version?

Reminder: to test the "DPC++ version uplift", you will need to create a branch https://github.com/KhronosGroup/SYCL-CTS/ repository directly.

**Review by keryell — APPROVED** [review]
Thanks!

**Pull request merged**
