### PR TITLE
Bump dpcpp version in ci

### PR DESCRIPTION
**Pull request by againull**
This version of the DPCPP contains a fix for get_native_mem() return
type.

### CODE REVIEW

**Comment by psalz** [comment]
Thanks, unfortunately the PR needs to originate from a branch local to this repository in order to have access to the necessary secrets for rebuilding the containers. Done in #341.

**Comment by bader** [comment]
> Thanks, unfortunately the PR needs to originate from a branch local to this repository in order to have access to the necessary secrets for rebuilding the containers. Done in #341.

It would be great to have a pre-commit check for that.

**Comment by psalz** [comment]
> > Thanks, unfortunately the PR needs to originate from a branch local to this repository in order to have access to the necessary secrets for rebuilding the containers. Done in #341.
> 
> It would be great to have a pre-commit check for that.

Not sure I'm following, what would you want to check for at commit-time?

**Comment by bader** [comment]
"PR needs to originate from a branch local to this repository in order to have access to the necessary secrets for rebuilding the containers."

**Comment by psalz** [comment]
Ah okay, so you mean more like a hint instead of a check (since we don't know what remote branch the commit will end up being pushed to).

**Comment by bader** [comment]
I had something like this in my mind:
```c++
if (current_repo == KhronosGroup/SYCL-CTS) // i.e. PR is opened for Khronos repository and not for a private fork
  if (modified_file == .github/workflows/cts_ci.yml) // i.e. CI is going to build a new image and source branch must be local.
    if (source_branch_repo != KhronosGroup/SYCL-CTS) // i.e. PR source branch is originated from a fork
      close PR with a comment that this PR can't be tested and it must be re-opened using local branch
```

**Comment by psalz** [comment]
Ah, now I understand, you mean a GitHub workflow. I was assuming you meant a pre-commit hook, i.e., on the git level. Yes that would be nice to have!

**Pull request closed without merging**
