### PR TITLE
Remove invalid use of get_pointer on placeholder accessor

### PR DESCRIPTION
**Pull request by steffenlarsen**
The SYCL specification states that get_pointer on an accessor or local_accessor can only be called inside a command. This commit fixes a use of get_pointer outside a command. Additionally it moves the surrounding code out of the encapsulating submission.

### CODE REVIEW

**Comment by keryell** [comment]
It is unclear to me where `get_pointer` is.

**Comment by steffenlarsen** [comment]
`get_pointer` is the method tested in `test_accessor_ptr`. Other tests use these on `host_accessor` which is perfectly valid.

**Comment by steffenlarsen** [comment]
> Doesn't this reduce the amount of testing for other kinds of accessors as well?

The test explicitly calls the check on a placeholder accessor and the info text for the case states so too. We shouldn't be hitting the case for `host_accessor` or the like.

**Comment by bader** [comment]
@keryell, do you have any follow-up questions?

**Review by keryell — APPROVED** [review]
Thanks.

**Pull request merged**
