### PR TITLE
get_property() exception tests for buffer and queue

### PR DESCRIPTION
**Pull request by AmirIpma**
Added checks for `sycl::buffer` and `sycl::queue` `get_property()` member function `errc::invalid` exception when trying to get a property which object does not have.

### CODE REVIEW

**Review by keryell — APPROVED** [review]
Thanks.

**Comment by bader** [comment]
@AmirIpma, please, resolve merge conflicts.

**Review by keryell — APPROVED** [review]
Thanks.

**Comment by AmirIpma** [comment]
> @AmirIpma, please, resolve merge conflicts.

Resolved.

**Pull request merged**
