### PR TITLE
Fix sub_group test

### PR DESCRIPTION
**Pull request by KornevNikita**
Passing sub_group instances captured from outside is UB.

### CODE REVIEW

**Comment by keryell** [comment]
I am unsure the problem is what you describe, since technically in a single task there is only 1 work-item, so there cannot be anything in-between.
But I agree that using subgroups captured from outside is kind of surprising.

**Comment by bader** [comment]
> I am unsure the problem is what you describe, since technically in a single task there is only 1 work-item, so there cannot be anything in-between.

Great, so you agree with changing `single_task` to `parallel_for`. Right?

> But I agree that using subgroups captured from outside is kind of surprising.

My guess is the description refers the deleted line 125. After switching to `parallel_for` we have more than 1 work-item. 

@keryell, what would you like to improve in this PR to approve the merge? Just description?

**Comment by KornevNikita** [comment]
@keryell the problem is here:
`But I agree that using subgroups captured from outside is kind of surprising.`
Probably my commit message is a bit confusing. Yes, I mean taking the sub_group instance from one command_group and then passing it to another is wrong - so it leads to wrong test results.

**Review by ProGTX — APPROVED** [review]

**Review by keryell — APPROVED** [review]
Thanks!

**Pull request merged**
