### PR TITLE
Fix accessor using unsuitable property

### PR DESCRIPTION
**Pull request by KornevNikita**
Accessor shouldn't use buffer::property.
It looks like there is no real need for `properties` to contain any property, as the test just checks all possible constructors.

### CODE REVIEW

**Comment by KornevNikita** [comment]
For some reason the runner is reaching the time limit.

**Comment by AlexeySachkov** [comment]
> For some reason the runner is reaching the time limit.

It seems like CI attempts to build *all* the CTS tests, which takes a while. Not sure why, because `ccache` should be in place and in general we should probably only re-build affected suites, not all of them

**Comment by KornevNikita** [comment]
@bader hi, how should we proceed here?

**Comment by bader** [comment]
> @bader hi, how should we proceed here?

Pass CI + get approval from non-Intel implementer => merge PR.

Are you asking something else?

**Comment by KornevNikita** [comment]
> > @bader hi, how should we proceed here?
> 
> Pass CI + get approval from non-Intel implementer => merge PR.
> 
> Are you asking something else?

Yes:) The patch can't pass CI. Looks like it builds the whole project and reaches the timelimit.

**Comment by bader** [comment]
> Yes:) The patch can't pass CI. Looks like it builds the whole project and reaches the timelimit.

I see at least two options to investigate:
- figure out why ccache doesn't work for your PR. NOTE: it works here - https://github.com/KhronosGroup/SYCL-CTS/pull/966.
- speed up the build of the whole project to fit into GitHub Actions limits.

**Review by keryell — APPROVED** [review]
Thanks.

**Comment by KornevNikita** [comment]
@bader can we treat the current pre-commit status as passed? Looks like the build was successful, the workflow just failed the "Post Set up ccache" step (I guess due to time limit?). Can we merge this?

**Comment by bader** [comment]
I hope https://github.com/KhronosGroup/SYCL-CTS/pull/982 will fix problems with `ccache`.

**Pull request merged**
