### PR TITLE
Generate clamp inputs according to precondition in the spec

### PR DESCRIPTION
**Pull request by lbushi25**
This PR aims to modify input generation for the clamp function tests which require its third argument to be greater than or equal to its second argument in every dimension as per the spec. Without this PR the input generation is completely random and not restricted according to the above conditions. A small bug has also been fixed where a local map variable was left uninitialized and it was causing random test failures in the math_builtin_api suite.

### CODE REVIEW

**Comment by lbushi25** [comment]
@AlexeySachkov FYI

**Comment by keryell** [comment]
Ouch!
While you are here, can you move some knowledge of your PR description as some comments in your code so future generation of readers will get the idea?

**Comment by lbushi25** [comment]
> Ouch! While you are here, can you move some knowledge of your PR description as some comments in your code so future generation of readers will get the idea?

Sure!

**Comment by lbushi25** [comment]
Update: Made a small bug fix in util/math_helper.h where a map variable was left uninitialized.

**Review by keryell — APPROVED** [review]
Thanks for the fix plus the teaching comments!

**Pull request merged**
