### PR TITLE
Enabled accessor tests partially and fix bugs

### PR DESCRIPTION
**Pull request by aleksmesh**
Enabled accessor tests partially and fix bugs in accessor_api_common.h and accessor_implicit_conversions.h.

### CODE REVIEW

**Comment by bader** [comment]
> The hosted runner: GitHub Actions 14 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

I think the root cause of this error is "CPU/Memory starvation" initiated by enabling compilation of accessor test cases. @aleksmesh, is it possible to mitigate this issue by reducing the amount of code in a single compilation unit (might not help if the problematic step is linking)?
Building in one thread might be helpful, but on the other hand it increases the build time and there is a risk to hit the time limit for a GitHub Action job.

It's worth raising this topic with DPC++ developers - https://github.com/intel/llvm/discussions.

**Comment by aleksmesh** [comment]
> @aleksmesh, is it possible to mitigate this issue by reducing the amount of code in a single compilation unit (might not help if the problematic step is linking)? Building in one thread might be helpful, but on the other hand it increases the build time

I thought so, the problem is in the big source code files. Thanks for the advice!

**Comment by aleksmesh** [comment]
@bader It seems that CI is now passing without a crash.

**Review by keryell — APPROVED** [review]
Thanks for the refactoring.

**Comment by mmoadeli** [comment]
@bader any reason not to have this merged? It will help evaluating the status of accessor 2020 features.

**Pull request merged**
