### PR TITLE
Add tests for SYCL 2020 host_accessor API

### PR DESCRIPTION
**Pull request by kopylovanat**
This PR depends on https://github.com/KhronosGroup/SYCL-CTS/pull/320 because of common code (merged).

### CODE REVIEW

**Review by andreyromanof — COMMENTED** [review]
LGTM

**Comment by keryell** [comment]
There are some merge conflicts to resolve first.

**Comment by vasilytric** [comment]
> There are some merge conflicts to resolve first.

@keryell All merge conflicts has been resolved

**Comment by bader** [comment]
@kopylovanat, we recently bumped DPC++ compiler version. Could you merge with the `SYCL-2020` branch to re-test this change with DPC++ compiler, please?

**Pull request merged**
