### PR TITLE
Set INTERFACE_LINK_OPTIONS for Clang

### PR DESCRIPTION
**Pull request by alan-forbes-cp**
Set specific INTERFACE_LINK_OPTIONS option for Clang.

### CODE REVIEW

**Comment by bader** [comment]
@alan-forbes-cp, could you elaborate on the motivation for this change, please?
I don't get the reasons to remove `-fsycl-device-code-split=per_source` option. AFAIK, it improves compilation time for the tests like `vector_*` by splitting huge device module into smaller parts.

**Comment by alan-forbes-cp** [comment]
Apologies @bader - that commit was incorrect. It should apply to CUDA only. I have updated the PR accordingly. Thanks.

**Comment by bader** [comment]
@alan-forbes-cp, could you clarify why this change is needed for CUDA, please?

**Comment by alan-forbes-cp** [comment]
@bader The option is not currently supported for CUDA and causes a CTS build fail as a result.

**Comment by bader** [comment]
Thanks for clarification. Could you it to the cmake file as a comment, please?

Do you know if there are plans to support this feature in future? Should we file an issue to enable this support?

**Comment by alan-forbes-cp** [comment]
Done. Support has been discussed informally - but there are no firm plans at the moment to my knowledge. So - yes - please file an issue.

Thanks!

**Comment by bader** [comment]
@keryell, @illuhad are you interested in reviewing changes in CMake configuration files for the implementation from `intel/llvm`?

**Comment by keryell** [comment]
> @keryell, @illuhad are you interested in reviewing changes in CMake configuration files for the implementation from `intel/llvm`?

Thanks for the invite.
I am not familiar with this...
Just curious to have somthing talking about OpenCL inside a test for CUDA only... :-)

**Comment by illuhad** [comment]
Same here, also wondering about OpenCL inside the CUDA section...

**Comment by bader** [comment]
@alan-forbes-cp should know better, but it might be related to this issue: https://github.com/intel/llvm/issues/1559.

**Comment by Ruyk** [comment]
It is related to https://github.com/intel/llvm/issues/1559. The DPC++ compiler needs the OpenCL symbols and headers somewhere even when using CUDA, but is not used at runtime.

**Comment by alan-forbes-cp** [comment]
Comments updated as requested. Thanks!

**Pull request merged**
