### PR TITLE
Add comments with links to issues and to PRs

### PR DESCRIPTION
**Pull request by aleksmesh**
Add comments with links to issues and to PRs for tests/accessor

### CODE REVIEW

**Comment by ProGTX** [comment]
Is this something we want to have in the CTS since it's very specific to just one implementation?

**Comment by kopylovanat** [comment]
> Is this something we want to have in the CTS since it's very specific to just one implementation?

@ProGTX 
But since these `#ifndef`'s are also specific to implementations, maybe it would be good to add links when possible, to keep track when it can be enabled?

**Review by keryell — APPROVED** [review]
Great idea.
I love that!

**Comment by bader** [comment]
@ProGTX, do you have any objections to add such comments? There are a few other PRs with similar comments, and I'd like to understand your position before merging them.

**Comment by fraggamuffin** [comment]
adding a link is good
also add a line to coding guideline

**Comment by fraggamuffin** [comment]
wait for Peter

**Pull request merged**
