### PR TITLE
Improved data type coverage for stream

### PR DESCRIPTION
**Pull request by kopylovanat**
Changed test name stream_api to stream_api_core to allow it to be run separately from other stream_api tests.

Added type coverage for
- id<dim = 1,2>, range<dim = 1,2>, item<dim = 1,2>, nd_item<dim = 1,2>,
  group<dim = 1,2>, nd_range<dim = 1,2>, h_item<dim = 1,2>
- stream_manipulator::flush
- vec<typename T, int numElements = (1, 2, 3, 4, 8 or 16)>
where T = (char, signed char, unsigned char, int, unsigned int, short,
unsigned short, long int, unsigned long int, long long int, unsigned
long long int, cl_char, cl_uchar, cl_int, cl_uint, cl_short,
cl_ushort, cl_long, cl_ulong, byte, float, double, half, cl_float,
cl_double, cl_half)

Added const correctness check

Remaining gap (test coverage): get_size() result correctness,
                               get_work_item_buffer_size()
                               exceeding totalBufferSize and workItemBufferSize,
                               actual console output verification
Possible remaining gaps (type coverage): vec<cl_bool, N>, vec<bool, N>

### CODE REVIEW

**Comment by bader** [comment]
@ProGTX, @illuhad, could you take a look, please?

**Review by bader — CHANGES_REQUESTED** [review]

**Review by bader — APPROVED** [review]

**Review by keryell — APPROVED** [review]
Good improvement!

**Comment by bader** [comment]
@ProGTX, @illuhad, could you take a look, please?

**Review by ProGTX — APPROVED** [review]
This doesn't work with ComputeCpp, but it seems to be an internal bug. The patch looks good otherwise.

**Pull request merged**
