### PR TITLE
Remove dependency on OpenCL from queue test

### PR DESCRIPTION
**Pull request by bader**

### CODE REVIEW

**Comment by bader** [comment]
The intent is to avoid using OpenCL API directly in SYCL tests except `opencl_interop`.

**Comment by AerialMantis** [comment]
That makes sense, we generally tried to restrict the OpenCL API calls to the interop tests, but some of the non-interop tests still required checks on `get` such as this.

Rather than removing it, could you move the check to `opencl_interop` instead?

**Comment by keryell** [comment]
This reminds me the private https://gitlab.khronos.org/sycl/conformance-testsuite/issues/74

**Comment by bader** [comment]
@AerialMantis, https://github.com/KhronosGroup/SYCL-CTS/pull/8/commits/82558f573862a5cc872c2bd587dde17646613cb8 should address your [comment](https://github.com/KhronosGroup/SYCL-CTS/pull/8#issuecomment-527887472).

**Comment by fraggamuffin** [comment]
Sept 9:
*  need Gordon to approve moving the functionality from one test to another - opencl INterop
*  reviewed change , this is the only change left

**Comment by AerialMantis** [comment]
This looks good to me, thanks @bader

**Pull request merged**
