### PR TITLE
Migrate CTS to Catch2 Testing Framework

### PR DESCRIPTION
**Pull request by psalz**
As decided in the WG, we will be migrating the CTS away from the existing custom-built testing framework to [Catch2](https://github.com/catchorg/Catch2). This will allow us to write more conventional, fine-grained test cases with natural language descriptions, hopefully making it both easier to comprehend existing tests as well as write new ones.

Going forward, instead of looking like this...
```c++
class event_constructors : public util:test_base {
  void run(util::logger& log) override {
    // (... more tests)
    // check equality operator
    {
      cts_selector selector;
      auto queue = util::get_cts_object::queue(selector);

      auto eventA = get_queue_event<class event_constructors_6>(queue);
      cl::sycl::event eventB(eventA);
      auto eventC = get_queue_event<class event_constructors_7>(queue);
      eventC = eventA;
      auto eventD = get_queue_event<class event_constructors_8>(queue);

      if (!(eventA == eventB)) {
        FAIL(log, "event equality does not work correctly (copy constructed)");
      }
      if (!(eventA == eventC)) {
        FAIL(log, "event equality does not work correctly (copy assigned)");
      }
      // (... more checks)
      queue.wait_and_throw();
    }
    // (... more tests)
  }
}
```

...a test case will look more like this:
```c++
TEST_CASE("sycl::event supports equality operators") {
  cts_selector selector;
  auto queue = util::get_cts_object::queue(selector);

  auto eventA = get_queue_event<class event_constructors_6>(queue);
  cl::sycl::event eventB(eventA);
  auto eventC = get_queue_event<class event_constructors_7>(queue);
  eventC = eventA;
  auto eventD = get_queue_event<class event_constructors_8>(queue);

  CHECK(eventA == eventB);
  CHECK(eventA == eventC);
  CHECK_FALSE(eventA != eventB);
  CHECK_FALSE(eventA != eventC);
  CHECK_FALSE(eventC == eventD);
  CHECK(eventC != eventD);

  queue.wait_and_throw();
}
```

Other benefits that come with Catch2 include:
- Smart assertion macros with great error reporting
- `SECTION`s to elegantly express different combinations of testing logic that share common setup and/or teardown code
- Type parametrized (templated) test cases
- ...and more. See the [Catch2 documentation](https://github.com/catchorg/Catch2/tree/devel/docs) for a full overview of all available features.

## Migration Strategy

The CTS is already quite large (> 50k LoC) and re-writing all tests from scratch at once is infeasible; an incremental strategy is needed.

While Catch2 will enable a new way of writing tests going forward, this is not what this PR does. In fact, very little (if anything) changes about the tests themselves. Instead, this PR simply replaces all of the CTS' internal plumbing with Catch2 (see below for a more detailed description of what that entails). **This means that all existing tests should still work as they did before**.

I've created a dedicated branch `catch2` within this repository that will house the Catch2 version of the CTS. This should make it easier to collaborate on this, for example, other people can create pull requests targeting the Catch2 branch. This way we can experiment with migrating existing tests and writing new tests while addressing outstanding questions and concerns. I will keep this branch up-to-date with the `SYCL-2020` branch, merging new tests as they come in. Once everything is ready, it should be merged back into the `SYCL-2020` branch.

## User-visible Changes

As already mentioned, very little changes about the user-facing API (where *user* refers to anyone writing tests for the CTS). The cornerstone of the legacy API, the `FAIL` macro, has been mapped to Catch2 and continues to work the same way it did before. Well, almost: It is no longer possible to use it as an expression (`return FAIL(...)`), however I only found one instance of that. Furthermore the first parameter (`log`) is now optional and can (and should) be omitted. Additionally the macro now supports `iostream`-style streaming of values: `FAIL("value is " << my_value)`.

That being said, going forward the `FAIL` macro should be used a lot more sparingly than it was in the past. The now very common pattern

```c++
if(condition != "met") {
  FAIL("condition was not met");
}
```

should be replaced by an assertion macro such as `CHECK(condition == "met")`. Other than being a lot terser, this has the important benefit that the Catch2 runtime can take note of the assertion and report it even if it succeeded:

```
./bin/test_device
===============================================================================
All tests passed (82 assertions in 3 test cases)
```

## Internal Changes

Replacing the legacy runtime with Catch2 mostly involves three steps:
1. Registering existing test cases with the Catch2 runtime
2. Mapping existing macros and utilities to Catch2
3. Removing a lof of now unused helper classes

Registering existing test cases with the Catch2 runtime uses the same mechanism as the legacy runtime: The `util::test_proxy<TEST_NAME> proxy;` created at the bottom of every legacy test file (where `TEST_NAME` refers to a class extending from `util::test_base`). Each proxy creates a single Catch2 test case that is additionally tagged with the `[legacy]` tag (a Catch2 feature for organizing test cases):

```
 ./bin/test_device --list-tests
All available test cases:
  device_api
      [legacy]
  device_constructors
      [legacy]
  device_info
      [legacy]
3 test cases
```

As already mentioned, most test cases rely on the `FAIL` macro to implement assertion logic. There are however a few other macros such as `CHECK_VALUE` defined in `tests/common/macros.h`, which I've all mapped to equivalent Catch2 logic as well.

Finally, as part of the transition, the following classes are being removed: `cmdarg`, `collection`, `csv`, `test_manager`, `executor`, `opencl_helper`, `printer`.

## Feature Parity

Catch2 brings with it a lot of new features on both the API side as well as for controlling how tests are being run and results are reported. Nevertheless we have to ensure that all existing capabilities are retained or adequately replaced. I've come up with the following list, please let me know if you find anything missing:

- [x] Generate conformance report: Still works.
- [x] Generate JUnit report: Previously we relied on the `runtests.py` script to generate an XML report; Catch2 supports this out of the box. As far as I can tell there is no reason to keep the Python script around, so I've removed it.
- [x] Filtering the set of executed test cases: Catch2 supports both command line and file-based filters, and is more flexible at that.
- [x] Output results to file: Supported with the `--out` option.

## Outstanding TODOs

While the transparent migration is already done with this initial set of changes, there are still several things to be done before we can merge:

- [x] FEEDBACK: I encourage everyone, especially frequent contributors (cc @vasilytric, @kopylovanat, @yuriykoch) to try working with this new setup. In particular, try to either convert an existing test or implement a brand new test case with the new idiomatic Catch2 approach (`TEST_CASE(...)`).
- [x] Compilation on Windows: Unfortunately I haven't managed to come up with a working setup for either of the three SYCL implementations that allows me to compile the CTS on Windows. Maybe someone who's already working on Windows could help me out here (cc @yuriykoch?). 
- [x] Build times: As far as I can tell, build times are not significantly affected by this change (unfortunately they can fluctuate quite wildly on GitHub's hosted CI runners).

Finally, I've taken this opportunity to also rewrite the README from scratch.

### CODE REVIEW

**Comment by yuriykoch** [comment]
@psalz Sorry for the late response.
I've been using the following sequence for windows compilation:

- Setup environment using the https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md and compiler sources from the https://github.com/intel/llvm/releases using separate command windows to setup the different runtimes
- Set up the environment variable `DPCPP_BUILD` to point to the `%DPCPP_HOME%\build` subdir
- Run cmake
```
cd build
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DOpenCL_LIBRARY=%DPCPP_BUILD%\lib\OpenCL.lib -DOpenCL_INCLUDE_DIR=%DPCPP_BUILD%\include\sycl -DSYCL_IMPLEMENTATION=DPCPP -DDPCPP_INSTALL_DIR=%DPCPP_BUILD% "-DDPCPP_FLAGS=-fsycl" ..
```
AFAIK ninja should work either.
-  Compile and link
```
set VERBOSE=1
nmake test_id
```
Looks like currently there is a caveat for windows compilation, so if there is no executable after a "[100%] Built target test_id" message then the linkage stage commands should be copied and re-run manually
- Run
```
@setlocal
@set PATH=%DPCPP_BUILD%\bin;%PATH%
.\bin\test_id --options
@endlocal
```

**Review by keryell — APPROVED** [review]
This a well described PR! :-)
I like the idea of changing only the testing infrastructure and not the tests themselves for now.

**Comment by psalz** [comment]
Thanks @yuriykoch, turns out last time I tried I was still running into that `/subsystem:console` linker flag bug that was fixed a while back, plus I wasn't sure how to properly set up OpenCL. Well anyway, I got everything to compile with a recent version of DPC++, so I will mark Windows support as done ✅!

**Review by ProGTX — APPROVED** [review]

**Review by bader — APPROVED** [review]
@vasilytric, @kopylovanat, @yuriykoch, please, review.

**Comment by kopylovanat** [comment]
I tried to convert buffer tests to catch2 and for the most part it seems to be able to be mapped OK, but I have a question now. How test cases, that uses different translation units by design (e.g. for fp16 and fp64 types or for testing with external functions), should be converted there?

**Comment by psalz** [comment]
> I tried to convert buffer tests to catch2 and for the most part it seems to be able to be mapped OK, but I have a question now. How test cases, that uses different translation units by design (e.g. for fp16 and fp64 types or for testing with external functions), should be converted there?

Thanks for giving it a try! For fp16/fp64 I see several options:
- Use [type parametrized test cases](https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#type-parametrised-test-cases), for example `TEMPLATE_LIST_TEST_CASE` with a type list that is adjusted based on whether fp16/fp64 are enabled.
- Wrap `TEST_CASE`s in `#ifdef SYCL_CTS_ENABLE_[HALF|DOUBLE]_TESTS` (that's a bit ugly, though).
- Just leave them as is, in a separate file. Maybe [tag](https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#tags) the tests cases with "[fp16]" or so, so they can more easily be grouped / run / excluded together.

But I'm not too sure either. We'll have to develop best practices over time, I think. What do you mean with "different translation units [...] for testing with external functions"? If you want you could also open a draft PR and we can continue the discussion there!

**Comment by fraggamuffin** [comment]
Approve

**Comment by kopylovanat** [comment]
> What do you mean with "different translation units [...] for testing with external functions"?

I was thinking about tests for specialization constants, for example, with SYCL_EXTERNAL function, that are in files [specialization_constants_external.h](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/tests/specialization_constants/specialization_constants_external.h) and [specialization_constants_separate_unit.cpp](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/tests/specialization_constants/specialization_constants_separate_unit.cpp)

Also there is tests for kernel_bundle that required containing in separate *.exe-file (were merged in https://github.com/KhronosGroup/SYCL-CTS/pull/218 )

For now it seems to me in both cases we can just keep them separate as is.

**Comment by bader** [comment]
@psalz, do you mind if we delete `catch2` branch?

**Comment by psalz** [comment]
Not at all, I thought I had already deleted it. Done!

**Pull request merged**
