### PR TITLE
[CI] Uplift DPC++ version to 0267c1b.

### PR DESCRIPTION
**Pull request by bader**

### CODE REVIEW

**Comment by bader** [comment]
@steffenlarsen, could you take a look at compilation issues with the new dpcpp compiler, please? Let me know if there is anything I can help with to fix these.

**Comment by kopylovanat** [comment]
@bader I think compilation issues caused by obsolete usage of accessor::get_pointer to get multi_ptr that is fixed in this patch https://github.com/KhronosGroup/SYCL-CTS/pull/668

**Review by keryell — APPROVED** [review]
I have no idea, but I am not against.

**Comment by bader** [comment]
> @bader I think compilation issues caused by obsolete usage of accessor::get_pointer to get multi_ptr that is fixed in this patch #668

#668 is merged, but now dpc++ crashes while compiles multi_ptr tests. I filed a bug report here: https://github.com/intel/llvm/issues/9745.

**Pull request merged**
