### PR TITLE
Cover gaps with checks for zero dimension accessor

### PR DESCRIPTION
**Pull request by aleksmesh**
Add checks for zero dimension sycl::accessor

### CODE REVIEW

**Review by ProGTX — APPROVED** [review]

**Comment by bader** [comment]
@aleksmesh, could you resolve merge conflicts, please?

**Comment by aleksmesh** [comment]
> @aleksmesh, could you resolve merge conflicts, please?

Done

**Comment by bader** [comment]
> SYCL-CTS/tests/accessor/accessor_common.h:798:53: error: no member named 'decorated' in namespace 'cl::sycl::access'

@aleksmesh, ComputeCPP and hipSYCL both do not support `sycl::access::decorated` enumeration yet. Can you disable unsupported part with the pre-processor, please?

**Comment by aleksmesh** [comment]
> > SYCL-CTS/tests/accessor/accessor_common.h:798:53: error: no member named 'decorated' in namespace 'cl::sycl::access'
> 
> @aleksmesh, ComputeCPP and hipSYCL both do not support `sycl::access::decorated` enumeration yet. Can you disable unsupported part with the pre-processor, please?

CI fixed

**Pull request merged**
